import { images } from "..";

export const assortii = [
  {
    id: 0,
    name: "Yamma",
    img: images?.yamma,
    bgColor: "#fff",
    numericPrice: 16.9,

    type: "Kana tempura (10tk)\nCalifornia maki (10tk)\nEbi tempura maki (10tk)",
  },
  {
    id: 1,
    name: "Crazy",
    img: images?.crazy,
    bgColor: "#fff",
    numericPrice: 18.9,
    type: "Kana tempura (10tk)\nCalifornia tempura (10tk) \nPhiladelphia (10tk) ",
  },
  {
    id: 2,
    name: "Veggie",
    img: images?.veggie,
    bgColor: "#fff",
    numericPrice: 20.9,
    type: "Veggie maki (10tk)\nKappa maki (10tk)\n Wakame maki (10tk)\n Veggie tempura (10tk) ",
  },
  {
    id: 3,
    name: "Hoso",
    img: images?.hosoSet,
    bgColor: "#fff",
    numericPrice: 24.9,
    type: "Sake Maki (10tk)\nKappa maki (10tk)\n Wakame maki (10tk)\n Unagi Maki (10tk)\nEbi tempura hoso Maki (10tk)  ",
  },
  {
    id: 4,
    name: "Samurai",
    img: images?.samurai,
    bgColor: "#fff",
    numericPrice: 28.9,
    type: "Kana tempura (10tk)\nCalifornia tempura (10tk) \nEbi tempura maki (10tk) \nPhiladelphia (10tk) \n ",
  },
  {
    id: 5,
    name: "Osushi",
    img: images?.osushi,
    bgColor: "#fff",
    numericPrice: 35.7,
    type: "California (10tk) \nSpicy maki (10tk) \nCalifornia tempura (10tk) \n Küpsetatud philadelphia maki (10tk) ",
  },
  {
    id: 6,
    name: "Friday",
    img: images?.friday,
    bgColor: "#fff",
    numericPrice: 36.9,
    type: "California (10tk) \nSpicy maki (10tk)\nKana tempura (10tk) \nCalifornia tempura (10tk) \nEbi tempura maki (10tk) ",
  },
];
export const nigiri = [
  {
    id: 7,
    name: "Ebi nigiri",
    img: images.ebiNigiri,
    bgColor: "#fff",
    numericPrice: 2.5,
    type: "Tiigerkrevett",
  },
  {
    id: 8,
    name: "Unagi nigiri",
    img: images.eelNigiri,
    bgColor: "#fff",
    numericPrice: 3.9,
    type: "Angerjas",
  },
  {
    id: 9,
    name: "Lõhe nigiri",
    img: images.salmonNigiri,
    bgColor: "#fff",
    numericPrice: 2.5,
    type: "Lõhe",
  },
  {
    id: 10,
    name: "Lõhe set nigiri",
    img: images.salmonSetNigiri,
    bgColor: "#fff",
    numericPrice: 6.9,
    type: "Lõhe (3tk)",
  },
];
export const uraMaki = [
  {
    id: 11,
    name: "Akita (10tk)",
    img: images?.akitaMaki,
    bgColor: "#fff",
    numericPrice: 8.95,
    type: "angerjas, tiigerkrevett, avokaado, toorjuust, unagi kaste, seesamiseemned",
  },
  {
    id: 12,
    name: "Dragon (10tk)",
    img: images.dragon,
    bgColor: "#fff",
    type: "angerjas, lumekrabi, avokaado, toorjuust, majonees, unagi kaste, seesamiseemned",
    numericPrice: 15.5,
  },
  {
    id: 13,
    name: "Ebi (10tk)",
    img: images.ebi,
    type: "tempura tiigerkrevett, toorjuust, jääsalat, mango-ingveri kaste, seesamiseemned",
    bgColor: "#fff",
    numericPrice: 8.5,
  },
  {
    id: 14,
    name: "California (10tk)",
    img: images?.california,
    bgColor: "#fff",
    type: "lumekrabi, kurk, avokaado, seesamiseemned",
    numericPrice: 8.9,
  },
  {
    id: 15,
    name: "Philadelphia (10tk)",
    img: images.phila,
    type: "lõhefilee, toorjuust, kurk, avokaado, seesamiseemned",
    bgColor: "#fff",
    numericPrice: 10.9,
  },
  {
    id: 16,
    name: "Veggie (10tk)",
    img: images?.veggieMaki,
    type: "kurk, avokaado, tomat, frillis salat, nori, riis, mango kaste, seesamiseemned",
    bgColor: "#fff",
    numericPrice: 7.9,
  },
  {
    id: 17,
    name: "Spicy (10tk)",
    img: images?.spicy,
    type: "kurk, avokaado, tomat, frillis salat, nori, riis, mango kaste, seesamiseemned",
    bgColor: "#fff",
    numericPrice: 7.9,
  },
];
export const hosoMaki = [
  {
    id: 18,
    name: "Unagi (10tk)",
    img: images?.unagiHoso,
    bgColor: "#fff",
    numericPrice: 7.9,
    type: "angerjas,  unagi kaste, seesamiseemned",
  },
  {
    id: 19,
    name: "Ebi (10tk)",
    img: images?.ebiHoso,
    bgColor: "#fff",
    numericPrice: 6.9,
    type: "tempura tiigerkrevett,  unagi kaste, seesamiseemned",
  },
  {
    id: 20,
    name: "Kappa (10tk)",
    img: images?.kappaHoso,
    bgColor: "#fff",
    numericPrice: 5.9,
    type: "kurk, seesamiseemned",
  },
  {
    id: 21,
    name: "Avokaado (10tk)",
    img: images?.avokaadoHoso,
    bgColor: "#fff",
    numericPrice: 5.9,
    type: "avokaado",
  },
  {
    id: 22,
    name: "Lõhe (10tk)",
    img: images?.salmonHoso,
    bgColor: "#fff",
    numericPrice: 5.9,
    type: "lõhefilee",
  },
  {
    id: 23,
    name: "Wakame (10tk)",
    img: images?.wakameHoso,
    bgColor: "#fff",
    numericPrice: 5.5,
    type: "merevetika salat, seesamiseemned",
  },
];
export const hotMaki = [
  {
    id: 24,
    name: "Philadelphia Hot (8tk)",
    img: images?.philadelphiaHot,
    bgColor: "#fff",
    numericPrice: 9.5,
    type: "lõhe, kurk, avokaado, toorjuust, riivjuust, majonees, seesamiseemned",
  },
  {
    id: 25,
    name: "Makao (8tk)",
    img: images?.makao,
    bgColor: "#fff",
    numericPrice: 9.9,
    type: "angerjas, avokaado, toorjuust, tiigerkrevett, terav kaste, unagi kaste, seesamiseemned",
  },
  {
    id: 26,
    name: "Nagasima (8tk)",
    img: images?.nagasima,
    bgColor: "#fff",
    numericPrice: 9.9,
    type: "lõhe, tiigerkrevett, lumekrabi, toorjuust, avokaado, unagi kaste, seesamiseemned",
  },
  {
    id: 27,
    name: "California hot (8tk)",
    img: images?.californiaHot,
    bgColor: "#fff",
    numericPrice: 9.9,
    type: "lumekrabi, avokaado, kurk, majonees, seesamiseemned",
  },
  {
    id: 28,
    name: "Shiitake (8tk)",
    img: images?.shiitake,
    bgColor: "#fff",
    numericPrice: 11.9,
    type: "shiitake seened (praetud), angerjas, avokaado, toorjuust, tiigerkrevett, unagi kaste, seesamiseemned",
  },
  {
    id: 29,
    name: "Kyoto Surimi (8tk)",
    img: images?.kyoto,
    bgColor: "#fff",
    numericPrice: 12.9,
    type: "lumekrabi, grill lõhe, toorjuust, kurk, majonees, terav kaste, seesamiseemned",
  },
];
export const tempuraMaki = [
  {
    id: 30,
    name: "California (10tk)",
    img: images?.californiaTempura,
    bgColor: "#fff",
    numericPrice: 8.9,
    type: "toorjuust, jääsalat, lumekrabi, unagi kaste, seesamiseemned",
  },
  {
    id: 31,
    name: "Golden (10tk)",
    img: images?.goldenTempura,
    bgColor: "#fff",
    numericPrice: 9.9,
    type: "lõhe, lumekrabi, avokaado, nori, riis, spicy kaste, seesamiseemned",
  },
  {
    id: 32,
    name: "Veggie (10tk)",
    img: images?.veggieTempura,
    bgColor: "#fff",
    numericPrice: 9.9,
    type: "kurk, avokaado, tomat, frillis salat, nori, riis, mango kaste, seesamiseemned",
  },
  {
    id: 33,
    name: "Kana (10tk)",
    img: images?.kanaTempura,
    bgColor: "#fff",
    numericPrice: 9.9,
    type: "kanafilee, jääsalat, juust, majonees, terav kaste,, seesamiseemned",
  },
  {
    id: 34,
    name: "Akita (10tk)",
    img: images?.akitaTempura,
    bgColor: "#fff",
    numericPrice: 14.9,
    type: "angerjas, tiigerkrevett, avokaado, toorjuust, unagi kaste, seesamiseemned",
  },
];
export const supisted = [
  {
    id: 35,
    name: "Tempura Krevett (5 tk)",
    img: images.tempuraShrimps,
    bgColor: "#fff",
    numericPrice: 5.5,
    type: "tiiger krevett panko ja tempura taignas, unagi kaste",
  },
  {
    id: 36,
    name: "Kalmaarirõngad (5 tk)",
    img: images.squid,
    bgColor: "#fff",
    numericPrice: 3.5,
    type: "kalmaarirõngad",
  },
  {
    id: 37,
    name: "Juustupallid (6tk)",
    img: images.cheeseballs,
    bgColor: "#fff",
    numericPrice: 3.5,
    type: "juust, tempura, panko",
  },
  {
    id: 38,
    name: "Chuka Ika Sansai salat",
    img: images.chukaIka,
    bgColor: "#fff",
    numericPrice: 5.5,
    type: "merevetika salat kalmaari ja ingveriga",
  },
  {
    id: 39,
    name: "Wakame salat",
    img: images.merevetika,
    bgColor: "#fff",
    numericPrice: 3.3,
    type: "merevetika salat",
  },
  {
    id: 40,
    name: "Unagi kaste",
    img: images.unagikaste,
    bgColor: "#fff",
    numericPrice: 1.2,
    type: "unagi kaste",
  },
  {
    id: 41,
    name: "Terav kaste",
    img: images.teravkaste,
    bgColor: "#fff",
    numericPrice: 1.2,
    type: "terav kaste",
  },
];
export const joogid = [
  {
    id: 42,
    name: "Coca-cola",
    img: images?.cola,
    bgColor: "#fff",
    numericPrice: 2.5,
    type: "Coca-cola 33cl",
  },
  {
    id: 43,
    name: "Coca-cola Zero",
    img: images?.colaZero,
    bgColor: "#fff",
    numericPrice: 2.5,
    type: "Coca-cola 33cl",
  },
  {
    id: 44,
    name: "Fanta",
    img: images?.fanta,
    bgColor: "#fff",
    numericPrice: 2.5,
    type: "Fanta 33cl",
  },
  {
    id: 45,
    name: "Sprite",
    img: images.sprite,
    bgColor: "#fff",
    numericPrice: 2.5,
    type: "Sprite 33cl",
  },
  {
    id: 46,
    name: "Mineraalvesi S.Pellegrino ",
    img: images.pellegrino,
    bgColor: "#fff",
    numericPrice: 2.5,
    type: "Mineraalvesi S.Pellegrino 50cl",
  },
];
export default {
  assortii,
  uraMaki,
  nigiri,
  hotMaki,
  tempuraMaki,
  supisted,
  joogid,
};
